apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swati-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/swati-d-bajpai/demo-argocd.git
    targetRevision: HEAD
    path: k8s-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: swati-ns
  syncPolicy:
    syncOptions:
      - syncTimeout=3s
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
